#+TITLE: Précisions diverses

* Précisions sur les fonctionnalités WYSIWYG attendues

Il y a plusieurs entrées dans le fichier [[https://github.com/bzg/findclub/blob/master/specifications.org][specifications.org]] qui
mentionnent une ergonomie en WYSIWYG :

** Créer un billet et l'éditer en WYSIWYG

Nous ne pouvons pas viser la complexité d'un logiciel de traitement de
texte comme MS Word, mais l'interface d'édition doit proposer les
fonctionnalités de base comme celles de [[https://www.tinymce.com/][TinyMCE]] :

- de créer des paragraphes ;

- de mettre en gras/en emphase/souligner un mot ;

- d'ajouter, de positionner et de redimensionner une image (en
  passant par un éditeur visuel WYSIWYG permettant de modifier les
  images de la banque d'images ou des images uploadées) ;

- de légender une image ou un média vidéo ;

- d'ajouter un lien en choisissant la cible (même onglet, nouvel
  onglet) ;

- d'insérer un média (vidéo) par simple sélection dans la base de
  données média ou par simple mention de l'URL (pour les vidéos
  sur Youtube, Vimeo, Dailymotion, etc.) ;

- de proposer un aperçu du résultat final ;

- d'indiquer quand la limite en nombre de signes est bientôt atteinte.

** Créer un dossier et choisir ses contenus en WYSIWYG

Un dossier est un « méta-contenu ».  Il est constitué d'au moins un
billet (son "édito") et de plusieurs éléments comme des images, des
vidéos, et d'autres ressources.

Un dossier peut être créé de trois manières :

- depuis le bouton « contribuer » accessible en home ;

- depuis une liste de suivi, en cliquant sur le plus d'un élément,
  lequel propose d'ajouter l'élément à un dossier existant ou à un
  nouveau dossier ;

- depuis la page de listing, avec un bouton "plus" ("ajouter au
  dossier") qui apparaît à côté des entrées listées, et qui permet
  d'ajouter l'élément à un dossier existant ou à un nouveau dossier.

En plus de cette vue listing, on peut envisager une vue "exploration"
qui permette de parcourir les dossiers et éléments comme on le ferait
dans un explorateur de fichier classique, avec la possibilité chaque
fois d'ajouter un élément au dossier en cours de création.

Cette fenêtre d'exploration donnerait un aperçu des contenus :

- l'icone représentant une image doit être une miniature de cette
  image ;

- l'icone représentant une vidéos doit être une miniature d'une image
  de la vidéo ;

- l'icone représentant un diaporama doit être une miniature d'une
  image de la diapositive.

** Créer un parcours en WYSIWYG

Un parcours est un dossier dont les éléments sont organisés dans le
temps et dans l'espace :

- dans le temps :: l'auteur d'un dossier peut « ordonner » les
     éléments, du premier au dernier.

- dans l'espace :: l'auteur d'un dossier peut associer des coordonnées
     géographiques (latitude et longitude) aux éléments du dossier.

L'édition en WYSIWYG d'un parcours signifie que le contributeur peut

1. ordonner temporellement les éléments par glisser-déposer sur une
   frise chronologique.

2. prendre un élément et le positionner sur un fond de carte
   naviguable pour que les coordonnées géographiques soient déduites
   de la position choisie par l'utilisateur.

À défaut d'une frise chronologique, le contributeur pourra donner un
numéro de priorité pour l'élément.

À défaut d'un positionnement manuel sur une carte, le contributeur
pourra renseigner la latitude et la longitude dans des champs.

** Créer un visuel en WYSIWYG

La création « en WYSIWYG » d'un visuel signifie que le contributeur
doit pouvoir uploader une image ou la choisir dans la bibliothèque de
médias de la plate-forme, et sélectionner une zone dans l'image
(cropping) qui a été mise en ligne.

** Visualiser un diaporama

Un « diaporama » peut désigner deux choses :

- Un type de contenu à part créé à partir de la mise en ligne d'un
  fichier PDF par un contributeur ; dans ce cas il existe une page
  permettant à tout utilisateur de faire défiler les pages du PDF de
  façon fluide.  Voir cette [[https://github.com/Jardin-des-Sciences/website/issues/31][issue github]] pour la discussion à ce
  sujet.

- Une façon de faire défiler plusieurs visuels d'un dossier.

* Gestion des droits des contenus

** Les droits des bases de données importées

| Base de données                      | Droits                |
|--------------------------------------+-----------------------|
| BNU                                  | Équivalent "CC-by-nc" |
| SCD                                  | Équivalent "CC-by-nc" |
| Gertrude                             | Équivalent "CC-by-nc" |
| Archives ouvertes de la connaissance | Document par document |
|--------------------------------------+-----------------------|
| Zoologie                             | ?                     |

** Une note sur le domaine public

En droit français, il est impossible de placer une oeuvre dans le
domaine public.  Donc un auteur d'un contenu original sur la
plate-forme ne peut choisir de mettre ce contenu dans le domaine
public.

** Un point sur les types de contenus

Les contenus peuvent être distingués en fonction de leur origine :

- *les contenus importés* : les droits sont ceux des éléments des bases
  de données.

- *les contenus contribués* : le choix est laissé aux contributeurs.

Les contenus peuvent être distingués en fonction de leur fonction sur
la plate-forme :

- *les contenus primaires* : il s'agit de toutes les contributions de
  type "dossier", "parcours", "visuel", "vidéo", "audio", etc.

- *les contenus secondaires ("sociaux")* : il s'agit des commentaires
  sur les contenus et de toutes les formes d'annotations.

Tous les contenus importés sont primaires.

Certains contenus contribués sont /primaires/ (ajout d'un billet, d'une
image, etc.) d'autres sont /secondaires/ (ajout d'un commentaire, d'une
question ou d'une réponse dans le forum, etc.)

Parmi les contenus primaires, nous distinguons encore :

- *les "collections"* : Dossiers, Parcours.

- *les "éléments"* : visuel, ressource documentaire, vidéo, audio, etc.

** Les droits d'auteur selon que le contenu est contribué ou importé

*** Les contenus importés

Les droits des contenus importés sont ceux d'origine : si un contenu
est sous droits d'auteur dans la base d'origine, ces droits sont les
mêmes dans leur version importée dans le site.

*** Les contenus contribués primaires

Il y a deux types de contenus contribués primaires, ceux dont on est
l'auteur direct, ceux qu'on reprend d'autres auteurs.  Un mécanisme à
la [[https://commons.wikimedia.org/wiki/Special:UploadWizard][Upload Wizard]] permet au contributeur de rapidement dire ce qu'il en
est pour un contenu qu'il ajoute.

Si le contenu appartient à quelqu'un d'autre, il doit préciser le ou
les auteur(s), la source et dire

- si c'est une licence creative commons*
- si c'est du droit d'auteur classique
- si c'est du domaine public
- si j'ai besoin d'aide pour savoir*

*=> entraîne un signalement de type "droits d'auteur à vérifier".

Si le contenu appartient au contributeur, on lui propose par défaut la
licence Creative Commons CC-by-sa-nc 4.0, mais il peut choisir une
autre licence Creative Commons :

- Creative Commons BY 4.0 :: similaire au domaine public, n'obligeant
     pas les internautes à placer le contenu réutilisé sous licence
     libre CC by-sa 4.0.

- Creative Commons BY-ND :: autorisant le partage et la
     commercialisation, mais interdisant les contenus dérivés.

- Creative Commons BY-NC :: autorisant le partage et les contenus
     dérivés, mais interdisant la commercialisation.

- Creative Commons BY-SA-ND :: autorisant le partage dans les mêmes
     conditions de licence, mais interdisant les contenus dérivés.

- Creative Commons BY-SA-NC :: autorisant le partage et les contenus
     dérivés, mais interdisant la commercialisation.

- Creative Commons BY-NC-ND :: équivalent au droit d'auteur classique
     et ne donnant aucun droit particulier aux internautes.

**** Précisions sur les liens avec les champs des types de contenus

Les indications qui concernent les droits d'auteur sont stockées dans
deux champs pour les contenus primaires: le champ "Droits d'auteur
(licence)" et le champ SA-ND-NC*.

La valeur par défaut pour le champ Creative Commons est {1, 0, 1}, qui
correspond à la licence Creative Commons by-sa-nc.

Une valeur standard pour le champ Droits d'auteur est "© Jardin de
botanique de Fontainebleau" indiquant à qui appartiennent les droits
d'auteur.  En général, ce champ est identique pour tous les items
importés d'une même base.

Si les deux champs sont incompatibles, le champ "Droits d'auteur"
prime.

*** Les contenus contribués secondaires

Pour les contenus contribués secondaires, ils sont tous placés sous
droit d'auteur classique.  En acceptant les Conditions Générales du
site, Les contributeurs autorisent le JDS à publier ces contenus sur
le site ou tout autre support sans contre-partie.

Les CGU précisent que les contributeurs sont responsables :

- de veiller à ne pas enfreindre la législation lors de l'import de
  contenus sur le site ;

- des contenus secondaires contribués : pas de grossièretés, etc.

Le site fonctionne comme un hébergeur des contenus contribués, non
comme l'auteur de ces contenus.

** Les droits d'auteur selon les types de contenus

*** Principe général

Les éléments ont un seul auteur et n'ont pas de contributeurs.

Les collections (dossiers et parcours) ont un seul auteur (celui qui
crée la collection) et peuvent avoir plusieurs contributeurs ; un
contributeur d'une collection est un utilisateur qui ajoute ou propose
d'ajouter un élément, selon que la modération est a posteriori ou a
priori.

*** Droits d'auteur sur les éléments

Les éléments ne sont pas collaboratifs : le contributeur les ajoute à
la plate-forme et gère seul leur contenu.

Si un utilisateur contribue à un élément avec du contenu secondaire
(un commentaire), les droits des deux contenus restent distincts.

Si un utilisateur contribue à un élément avec un conseil pris en
compte par le contributeur de l'élément (par exemple une légende sur
une image, une correction de faute d'orthographe), cela n'affecte pas
les droits de l'élément.

*** Droits d'auteur sur les collections

Les collections (dossiers et parcours) sont des façons collaboratives
de /présenter/ des éléments.  Elles ne constituent pas une oeuvre
originale qui permettrait à son contributeur initial ou aux suivants
de solliciter des droits particulier.

Le champ "Droits d'auteur (licence)" pour les dossiers et les parcours
désigne les droits s'appliquant pour les éléments dont les droits ne
sont pas précisés.

Par défaut, la valeur du champ "Droits d'auteur (licence)" pour les
dossiers est CC by-nc-sa 4.0.

Si des droits sont précisés pour les éléments, ceux-ci ont priorité
sur les droits des collections.

*** Droits d'auteur sur les ressources documentaires

Les droits sur les métadonnées des ressources documentaires ne doivent
pas être confondus avec les droits d'auteur associées à ces ressources.
Par exemple, des métadonnées peuvent être publiées en CC-by-sa alors
que les contenus qu'elles décrivent sont sous droit d'auteur classique.

** Protection par le droit des marques

La marque protège le logo et le nom du site.

[Question ouverte : est-ce que le design est protégé par ce dépôt de
marque ou par l'Université elle-même ?]

* Workflow pour l'inscription sur la plate-forme

** Moyens de s'inscrire sur la plate-forme

Tous les utilisateurs sont invités à devenir contributeur en créant un
compte sur la plateforme.

L'utilisateur peut demander la création d'un compte de trois façons :

- par email ;
- par Facebook ;
- Par Twitter.

Si la demande est faite par email, un email de confirmation est envoyé
à l'utilisateur à l'adresse renseignée, et l'utilisateur doit cliquer
sur un lien ce mail pour que la création du compte soit finalisée.

Si la demande est faite par Facebook ou Twitter, l'utilisateur est
redirigé vers ces plate-formes qui lui demandent de confirmer
l'utilisation de leur compte Facebook ou Twitter pour la création d'un
compte sur Osca(h)r.

** Champs de création de compte et permissions sur Facebook/Twitter

Lors de la création de compte par mail, seul un champ "adresse email"
est présenté à l'utilisateur.  Tant que l'email saisie dans ce champ
n'est pas conforme, l'utilisateur ne peut valider sa demande de
création de compte.

Lors de la création de compte via Facebook ou Twitter, la seule
permission demandée à l'utilisateur "Accéder aux informations de base
sur le compte".  Osca(h)r ne demande pas l'accès aux informations non
basiques comme les listes d'amis, la ville de naissance, etc.
Osca(h)r ne demande pas la permission de pouvoir écrire dans les
statuts Facebook ou Twitter.

** (Pré)validation des comptes contributeurs

L'administrateur peut éditer une liste de noms de domaines prévalidés.

C'est noms de domaines sont ceux pour lesquels la création de comptes
est prévalidée (voir le workflow ci-dessous).

Les items de cette listes supportent le "globbing", i.e. le matching
sur des patterns du genre "*gouv.fr".

La liste initiale en base de données est :

- unistra.fr
- *gouv.fr

** Workflow de validation des demandes d'inscription

- (1) l'utilisateur demande la création d'un compte

- (2) il valide la demande (par email ou par Facebook/Twitter)

- (3a) s'il utilise une adresse mail prévalidée, son compte est créé
  et il reçoit un mail lui demandant de compléter son profil

- (3b) s'il utilise une adresse mail non-prévalidée, l'administrateur
  reçoit une alerte et peut valider ou non la création de compte

- (3aa) si l'administrateur valide la création de compte, le compte
  est créé et l'utilisateur reçoit un mail lui demandant de compléter
  son profil 

- (3ab) si l'administrateur ne valide pas la création de compte,
  l'utilisateur reçoit un email lui indiquant que sa création de
  compte n'a pas été acceptée et l'invitant à contacter les
  administrateurs s'il veut des explications.

* Signalement de problèmes sur des contenus (fait)

Les problèmes à signaler sur les contenus peuvent être de plusieurs
ordres :

1. des problèmes de droit d'auteur (mauvaise licence)

2. des problèmes de contenu inapproprié (propos injurieux, etc.)

3. des problèmes techniques (mauvais affichage, etc.)

4. des problèmes scientifiques (erreur, etc.)

Quand il souhaite signaler un problème sur un contenu, l'utilisateur
(ou le contributeur) voit s'afficher une fenêtre modal lui demandant
de préciser la nature du problème parmi ces quatre possibilités.

Si c'est un *utilisateur non-connecté*, le formulaire lui propose trois
options : problème de droits d'auteur, problème technique, problème de
contenu inapproprié.

Si c'est un *contributeur* (utilisateur connecté), le formulaire lui
propose quatre options : les trois précédentes et la possibilité de
signaler un problème scientifique sur un contenu.

Une fois le choix effectué, on demande aux utilisateurs connectés leur
nom, leur adresse email, et quelques lignes d'explications ; pour les
contributeurs, on demande juste quelques lignes d'explications.

Les problèmes signalés portent soit sur des contenus primaires
(signalement accessible aux utilisateurs et aux contributeurs) soit
sur des commentaires (signalement accessible seulement aux
contributeurs).

Voici les différents types de problèmes :

- des problèmes de droit d'auteur :: dans ce cas, le problème remonte
     au contributeur et aux administrateurs.

- des problèmes de contenu inapproprié :: dans ce cas, le problème
     remonte au contributeur et aux administrateurs.  (Les contenus
     inappropriés peuvent concerner les contenus primaires et les
     contenus secondaires comme les commentaires.)

- des problèmes techniques :: dans ce cas, le problème remonte aux
     administrateurs.

- des problèmes scientifiques :: dans ce cas, le problème remonte au
     contributeur.  (Signalement accessible seulement aux
     contributeurs.)

* Informations générales sur les normes d'accessibilité

- http://www.accede-web.com : information générale
- http://references.modernisation.gouv.fr : référence gouvernement
- http://paypal.github.io/bootstrap-accessibility-plugin/demo.html :
  plugin pour bootstrap


