#+TITLE: Précisions diverses

* Précisions sur l'utilisation de la plate-forme pour le Web sémantique

La plate-forme doit exposer les données contribuées sous forme de
données sémantique (sparql endpoint), de façon à ce que ces données
soient moissonnées par un moteur comme Isidore, ou récupérée
directement.

Voir http://www.huma-num.fr/sites/default/files/guide-isidore.pdf

Le format exact des données à exposer est à définir.

* Précisions sur le signalement de problèmes sur des contenus

Les problèmes à signaler sur les contenus peuvent être de plusieurs
ordres :

1. des problèmes de droit d'auteur (mauvaise licence)

2. des problèmes de contenu inapproprié (propos injurieux, etc.)

3. des problèmes techniques (mauvais affichage, etc.)

4. des problèmes scientifiques (erreur, etc.)

Quand il souhaite signaler un problème sur un contenu, l'utilisateur
(ou le contributeur) voit s'afficher une fenêtre modal lui demandant
de préciser la nature du problème parmi ces quatre possibilités.

Si c'est un *utilisateur non-connecté*, le formulaire lui propose trois
options : problème de droits d'auteur, problème technique, problème de
contenu inapproprié.

Si c'est un *contributeur* (utilisateur connecté), le formulaire lui
propose quatre options : les trois précédentes et la possibilité de
signaler un problème scientifique sur un contenu.

Une fois le choix effectué, on demande aux utilisateurs connectés leur
nom, leur adresse email, et quelques lignes d'explications ; pour les
contributeurs, on demande juste quelques lignes d'explications.

Les problèmes signalés portent soit sur des contenus primaires
(signalement accessible aux utilisateurs et aux contributeurs) soit
sur des commentaires (signalement accessible seulement aux
contributeurs).

Voici les différents types de problèmes :

- des problèmes de droit d'auteur :: dans ce cas, le problème remonte
     au contributeur et aux administrateurs.

- des problèmes de contenu inapproprié :: dans ce cas, le problème
     remonte au contributeur et aux administrateurs.  (Les contenus
     inappropriés peuvent concerner les contenus primaires et les
     contenus secondaires comme les commentaires.)

- des problèmes techniques :: dans ce cas, le problème remonte aux
     administrateurs.

- des problèmes scientifiques :: dans ce cas, le problème remonte au
     contributeur.  (Signalement accessible seulement aux
     contributeurs.)

* Précisions sur les fonctionnalités WYSIWYG

Il y a cinq entrées dans le fichier [[https://github.com/bzg/findclub/blob/master/specifications.org][specifications.org]] qui mentionnent
le WYSIWYG :

** Créer un visuel en WYSIWYG

Pouvoir sélectionner une zone dans l'image qui a été mise en ligne.

** Créer un billet et l'éditer en WYSIWYG

Nous ne pouvons pas viser la complexité d'un logiciel de traitement de
texte comme MS Word, mais l'interface d'édition doit proposer les
fonctionnalités de base comme celles de [[https://www.tinymce.com/][TinyMCE]] :

 - de créer des paragraphes
 - de mettre en gras/en emphase/souligner un mot
 - d'ajouter, de positionner et de redimensionner une image (en
   passant par un éditeur visuel WYSIWYG permettant de modifier les
   images de la banque d'images ou des images uploadées)
 - de légender une image ou un média vidéo
 - d'ajouter un lien en choisissant la cible (même onglet, nouvel
   onglet) 
 - d'insérer un média (vidéo) par simple sélection dans la base de
   données média ou par simple mention de l'URL (pour les vidéos
   sur Youtube, Vimeo, Dailymotion, etc.)
 - de proposer un aperçu du résultat final
 - d'indiquer quand la limite en nombre de signes est bientôt
   atteinte

*** Import de documents .docx ou .odt pour les billets (?)

D'autre part, il doit être possible *d'importer un fichier .docx ou
.odt* qui sera nettoyé côté pour être ensuite affiché dans l'éditeur
WYSIWYG du site.  

Questions ouvertes :

- récupération du format - jusqu'où ?
- récupération des visuels ?
- surligner le texte qui dépasse du nombre de signes admis

** Créer un edito et l'éditer en WYSIWYG

Même chose que pour le billet, la seule différence étant que l'édito
est forcément associé à un dossier.

** Créer un diaporama et agencer l'ordre des diapositives en WYSIWYG

Un diaporama est constitué des éléments suivants :

- D'une ou plusieurs images ordonnées
- Du son accompagnant chaque image (optionnel)
- D'un timer pour chaque image (optionnel)
- D'une légende accompagnant chaque image (optionnel)
  
L'interface WYSIWYG pour le diaporama doit permettre

- d'ordonner les images par glisser-déposer ;

- d'ajouter des images de la base de données média, de son disque dur
  ou par un simple copier-coller d'un lien vers une image sur le Web
  ou par import d'un fichier (.pdf ou .pptx .odp) qui sera traité côté
  serveur pour en extraire une succession d'images ;

- d'associer un son (par enregistrement, upload ou lien web) à une
  image donnée ;

- d'ajouter un timer pour une image ;

- d'ajouter une légende pour une image ;

** Créer un dossier et choisir ses contenus en WYSIWYG

Un dossier est constitué d'au moins un billet (son "édito") et de
plusieurs éléments comme des images, des vidéos, et d'autres
ressources.

Un dossier peut être créé de deux manières :

- depuis une liste de suivi, en cliquant sur le plus d'un élément,
  lequel propose d'ajouter l'élément à un dossier existant ou à un
  nouveau dossier ;

- depuis la page de listing, avec un bouton "plus" ("ajouter au
  dossier") qui apparaît à côté des entrées listées, et qui permet de
  même d'ajouter l'élément à un dossier existant ou à un nouveau
  dossier.

En plus de cette vue listing, on peut envisager une vue "exploration"
qui permette de parcourir les dossiers et éléments comme on le ferait
dans un explorateur de fichier classique, avec la possibilité chaque
fois d'ajouter un élément au dossier en cours de création.

Cette fenêtre d'exploration donnerait un aperçu des contenus :

- l'icone représentant une image doit être une miniature de cette
  image ;

- l'icone représentant une vidéos doit être une miniature d'une image
  de la vidéo ;

- l'icone représentant un diaporama doit être une miniature d'une
  image de la diapositive.

* Comment encourager les primo-contributeurs ?

** Établir la liste des primo-contributeurs
** Établir le calendrier de leurs disponibilités
** Voir si on peut faire des ateliers restreints
* Quels droits sur quels contenus ?

** Les droits des bases de données importées

| Base de données                      | Droits                |
|--------------------------------------+-----------------------|
| BNU                                  | Équivalent "CC-by-nc" |
| SCD                                  | Équivalent "CC-by-nc" |
| Gertrude                             | Équivalent "CC-by-nc" |
| Archives ouvertes de la connaissance | Document par document |
|--------------------------------------+-----------------------|
| Zoologie                             | ?                     |

** Une note sur le domaine public

En droit français, il est impossible de placer une oeuvre dans le
domaine public.  Donc un auteur d'un contenu original sur la
plate-forme ne peut choisir de mettre ce contenu dans le domaine
public.

** Un point sur les types de contenus

Les contenus peuvent être distingués en fonction de leur origine :

- *les contenus importés* : les droits sont ceux des éléments des bases
  de données.

- *les contenus contribués* : le choix est laissé aux contributeurs.

Les contenus peuvent être distingués en fonction de leur fonction sur
la plate-forme :

- *les contenus primaires* : il s'agit de toutes les contributions de
  type "dossier", "parcours", "visuel", "vidéo", "audio", etc.

- *les contenus secondaires ("sociaux")* : il s'agit des commentaires
  sur les contenus et de toutes les formes d'annotations.

Tous les contenus importés sont primaires.

Certains contenus contribués sont /primaires/ (ajout d'un billet, d'une
image, etc.) d'autres sont /secondaires/ (ajout d'un commentaire, d'une
question ou d'une réponse dans le forum, etc.)

Parmi les contenus primaires, nous distinguons encore :

- *les "collections"* : Dossiers, Parcours.

- *les "éléments"* : visuel, ressource documentaire, vidéo, audio, etc.

** Les droits en fonction des types de contenus

*** Les contenus importés

Les droits des contenus importés sont ceux d'origine : si un contenu
est sous droits d'auteur dans la base d'origine, ces droits sont les
mêmes dans leur version importée dans le site.

*** Les contenus contribués primaires

Il y a deux types de contenus contribués primaires, ceux dont on est
l'auteur direct, ceux qu'on reprend d'autres auteurs.  Un mécanisme à
la [[https://commons.wikimedia.org/wiki/Special:UploadWizard][Upload Wizard]] permet au contributeur de rapidement dire ce qu'il en
est pour un contenu qu'il ajoute.

Si le contenu appartient à quelqu'un d'autre, il doit préciser le ou
les auteur(s), la source et dire

- si c'est une licence creative commons*
- si c'est du droit d'auteur classique
- si c'est du domaine public
- si j'ai besoin d'aide pour savoir*

*=> entraîne un signalement de type "droits d'auteur à vérifier.

Si le contenu appartient au contributeur, on lui propose par défaut
la licence Creative Commons CC-by-sa-nc 4.0, mais il peut choisir une
autre licence Creative Commons :

- Creative Commons BY 4.0 :: similaire au domaine public, n'obligeant
     pas les internautes à placer le contenu réutilisé sous licence
     libre CC by-sa 4.0.

- Creative Commons BY-ND :: autorisant le partage et la
     commercialisation, mais interdisant les contenus dérivés.

- Creative Commons BY-NC :: autorisant le partage et les contenus
     dérivés, mais interdisant la commercialisation.

- Creative Commons BY-SA-ND :: autorisant le partage dans les mêmes
     conditions de licence, mais interdisant les contenus dérivés.

- Creative Commons BY-SA-NC :: autorisant le partage et les contenus
     dérivés, mais interdisant la commercialisation.

- Creative Commons BY-NC-ND :: équivalent au droit d'auteur classique
     et ne donnant aucun droit particulier aux internautes.

**** Précisions sur les liens avec les champs des types de contenus

Les indications qui concernent les droits d'auteur sont stockées dans
deux champs pour les contenus primaires: le champ "Droits d'auteur
(licence)" et le champ SA-ND-NC*.

La valeur par défaut pour le champ Creative Commons est {1, 0, 1},
qui correspond à la licence Creative Commons by-sa-nc.

Une valeur standard pour le champ Droits d'auteur est "© Jardin de
botanique de Fontainebleau" indiquant à qui appartiennent les droits
d'auteur.  En général, ce champ est identique pour tous les items
importés d'une même base.

Si les deux champs sont incompatibles, le champ "Droits d'auteur"
prime.

*** Les contenus contribués secondaires

Pour les contenus contribués secondaires, ils sont tous placés sous
droit d'auteur classique.  En acceptant les Conditions Générales du
site, Les contributeurs autorisent le JDS à publier ces contenus sur
le site ou tout autre support sans contre-partie.

Les CGU précisent que les contributeurs sont responsables :

- de veiller à ne pas enfreindre la législation lors de l'import de
  contenus sur le site ;

- des contenus secondaires contribués : pas de grossièretés, etc.

Le site fonctionne comme un hébergeur des contenus contribués, non
comme l'auteur de ces contenus.

** Droits d'auteur sur les différents contenus

Les collections et éléments ont chaque fois *un seul auteur* et *un seul
contributeur* : l'auteur est indiqué dans le champ "Droits d'auteur" et
le contributeur est l'utilisateur ayant importé ou ajouté ce contenu.

Les éléments et les collections impliquent des contraintes différentes
pour la gestion des droits d'auteur.

*** Droits d'auteur sur les éléments

Les éléments ne sont pas collaboratifs : le contributeur les ajoute à
la plate-forme et gère seul leur contenu.

Si un utilisateur contribue à un élément avec du contenu secondaire
(un commentaire), les droits des deux contenus restent distincts.

Si un utilisateur contribue à un élément avec un conseil pris en
compte par le contributeur de l'élément (par exemple une légende sur
une image, une correction de faute d'orthographe), cela n'affecte pas
les droits des contenus.

*** Droits d'auteur sur les collections

Les collections (dossiers et parcours) sont des façons collaboratives
de /présenter/ des éléments.  Elles ne constituent pas une oeuvre
originale laquelle permettrait à un contributeur de solliciter des
droits particulier.

*** Droits d'auteur sur les ressources documentaires

Les droits sur les métadonnées des ressources documentaires ne doivent
pas être confondus avec les droits d'auteur associées à ces ressources.
Par exemple, des métadonnées peuvent être publiées en CC-by-sa alors
que les contenus qu'elles décrivent sont sous droit d'auteur classique.

** Protection par le droit des marques

La marque protège le logo et le nom du site.

[Question ouverte : est-ce que le design est protégé par ce dépôt de
marque ou par l'Université elle-même ?]

* Informations sur les normes d'accessibilité

- http://www.accede-web.com : information générale
- http://references.modernisation.gouv.fr : référence gouvernement
- http://paypal.github.io/bootstrap-accessibility-plugin/demo.html :
  plugin pour bootstrap

* Liste des pages statiques

- Conditions Générales d'utilisation

- Présentation générale du site (équivalent de About)

- Page d'explications pour la question des droits d'auteur et des
  licences.
  
* Fonctionnalités « gelées »
** Précisions sur les aspects de gamification et la liste des badges

 Voir https://groups.drupal.org/node/248868 pour l'implémentation Open
 Badges.

 Listes des actions de contribution, de leur importance et des seuils
 pour les "badges" (bronze/argent/or) :

 |                                                | Importance (/5) | Badge ?  | Points | Type           |
 |------------------------------------------------+-----------------+----------+--------+----------------|
 | Créer un dossier                               |               5 | 1/2/5    |        | Contenu        |
 | Créer un parcours                              |               5 | 1/2/5    |        | Contenu        |
 |------------------------------------------------+-----------------+----------+--------+----------------|
 | Ajouter un billet                              |               4 | 1/5/10   |        | Contenu        |
 | Ajouter un visuel                              |               4 | 1/5/10   |        | Contenu        |
 | Ajouter une ressource vidéo                    |               4 | 1/5/10   |        | Contenu        |
 | Ajouter une ressource diaporama                |               4 | 1/5/10   |        | Contenu        |
 |------------------------------------------------+-----------------+----------+--------+----------------|
 | Ajouter un élément à un dossier                |               3 | 1/10/20  |        | Contenu        |
 | Ajouter un élément à un parcours               |               3 | 1/10/20  |        | Contenu        |
 | Créer une entrée de glossaire                  |               3 | 1/10/20  |        | Contenu        |
 | Créer une question éditorialisée               |             2.5 | 1/15/30  |        | Contenu/Social |
 | Créer une entrée de FAQ                        |             2.5 | 1/15/30  |        | Contenu/Social |
 |------------------------------------------------+-----------------+----------+--------+----------------|
 | Créer un lien                                  |               2 | 1/20/40  |        | Contenu        |
 | Créer un événement                             |               2 | 1/20/40  |        | Social         |
 | Renseigner son profil à 80%                    |               2 | 10       |        | Social         |
 |------------------------------------------------+-----------------+----------+--------+----------------|
 | Faire un commentaire                           |               1 | 1/25/50  |        | Social         |
 | Poser une question sur le forum                |               1 | 1/25/50  |        | Social         |
 | Répondre à une question sur le forum           |               1 | 1/25/50  |        | Social         |
 | Soumettre un dossier/parcours pour être en une |               1 | 1/25/50  |        | Contenu/social |
 |------------------------------------------------+-----------------+----------+--------+----------------|
 | Suivre un autre utilisateurs                   |              .5 | 1/50/100 |        | Social         |
 | Être suivi par d'autres utilisateurs           |              .5 | 1/50/100 |        | Social         |
 |------------------------------------------------+-----------------+----------+--------+----------------|
 | Faire remonter des problèmes                   |               1 | 1/25/50  |        | Contenu        |

 (Voir la [[http://meta.stackexchange.com/questions/67397/list-of-all-badges-with-full-descriptions][liste des badges]] de Stackoverflow pour des idées.)

 On peut distinguer deux types de contributions, celles qui portent sur
 les contenus, celles qui portent sur les interactions sociales.  Par
 exemple : quelqu'un de peu suivi peut en revanche ajouter beaucoup de
 contenus, quelqu'un d'assez suivi peut ajouter des contenus avec
 parcimonie, etc.

 Le système de badge doit valoriser ces deux aspects de façon lisible.

 Par exemple, dès qu'un contributeur publie un dossier, il obtient 5
 points (équivalent au niveau d'importance de la création de dossier.)
 Au dossier suivant, encore 5 autres points.  Il ajoute un commentaire,
 un point supplémentaire.  Etc.

 Il y a d'un côté les points obtenus pour les contributions à des
 contenus, de l'autre les points obtenus pour des contributions
 sociales.  Les contributions double (portant sur le contenu et le
 social, comme les questions éditorialisées) donnent des points dans
 les deux catégories.

*** Fonction des badges

 Les points et les badges sont purement déclaratifs : ils ne permettent
 pas aux contributeurs d'accéder à des fonctions ou statuts particuliers.

 Du point de vue de l'interface, les badges ont trois effets :

 1. ils s'affichent quand un utilisateur en obtient un ;
 2. ils sont affichés dans le profil utilisateur ;
 3. les administrateurs peuvent tous les voir.

 Chaque accomplissement donne lieu à une alerte remerciant le
 contributeur pour sa contribution et lui indiquant le badge obtenu.

*** Qualificatifs (optionnel)

 Dans les contributions sociales, plusieurs profils :

 - le "curieux" : pose beaucoup de questions
 - "l'aidant" : propose beaucoup de réponses
 - le "liant" : organise des événements, contribue aux FAQs
 - le "leader" : est suivi par de nombreux utilisateurs
 - le "participant" : suit de nombreux utilisateurs

 Nous pourrons soit proposer ces qualifiatifs directement (comme sur
 Stackoverflow), soit les afficher en fonction des badges obtenus par
 ailleurs.

*** Utilité réelle des badges

 Le but n'est pas de "gamifier" complètement la plate-forme, mais
 d'avoir des repères (1) si les primo-contributeurs imaginent des
 récompenses intéressantes pour les contributeurs ou (2) si les
 administrateurs veulent s'adresser à un profil de contributeurs
 particulier.

 Par exemple, on teste une nouvelle fonctionnalité de forum : on
 enverra un mail aux 100 utilisateurs ayant le plus de points dans la
 catégorie "contribution sociale".

 Ou bien on organise un colloque, on invite les 100 contributeurs ayant
 le plus de points dans la catégorie contenu.

** Précisions sur la liste des attentes

 /Citation mail bzg 8 janvier :/

 #+BEGIN_QUOTE
    La "Liste des attentes" est une sorte de wishlist que l'auteur d'un
    dossier peut ajouter.  Il formule des demandes et si les futurs
    contributeurs y répondent, il les "coche".  Ça permet de connaître
    les besoins sur un projet, et l'état d'avancement.
 #+END_QUOTE

 Concrètement, une liste d'attente est un ensemble ordonné d'items
 possédant chacun deux champs : un champ texte "description" et un
 champ binaire 0/1 (pas fait / fait).

 Exemple:

 #+BEGIN_QUOTE
 #{:description "Corriger les fautes" 0
   :description "Ajouter des images" 1}
 #+END_QUOTE

* Rappel sur les itérations prévues

Le projet est découpé en quatre itérations :

1. identité et socle de données
2. fonctionnalités et navigation
3. rôle utilisateurs et contenus
4. fonctionnalités sociales
5. Webmastering et recettes

** Fonctions principales

| *Import* des données de bases existantes                          | Itération 1 |
| *Recherche et navigation* d'un utilisateur au sein de ces données | Itération 2 |
| *Contribution* des utilisateurs                                   | Itération 3 |

Les utilisateurs peuvent ajouter soit des éléments (une image, une
ressource documentaire), soit les rassembler en dossiers (nommés «
collections » dans le cahier des charges initial.)

* Résumé du cahier des charges par itération

** Itération 1 : accès au socle de données

Le cahier des charges de cette première itération :

- Création d'un module d'import des données de Gertrude dans la base
  de données du portail (ce qui demande d'avoir défini les données qui
  seront importées -- voir problème du /mapping/.)

- Mise en place d'un système pour l'import des autres bases en
  fonction de ce que nous savons d'elles (par exemple : quelles
  technologies sont utilisées pour les bases métiers ?)

- Construction d'une interface minimale sous Drupal pour la navigation
  au sein des données importées, ce qui demande d'avoir défini quelles
  données vont être exposées via l'interface.

  Note : l'interface minimale n'a pas besoin de correspondre au
  storyboarding final du site - c'est juste un "proof of concept"
  (POC) pour vérifier que les données sont correctement importées et
  accessibles.

** Itération 2 : navigation dans la base de données

- Finalisation des mockups et du storyboarding.

- Implémentation de l'interface de navigation finale.

** Itération 3 : fonctionnalités contributives
** Itération 4 : fonctionnalités sociales
* Notes diverses

- En page d'accueil, un affichage aléatoire pondéré sur l'ancienneté
  des billets et dossiers potentiellement à la une : les billets et
  dossiers les plus récents ont le plus de chances d'être tirés au
  hasard (voir [[https://github.com/Jardin-des-Sciences/website/issues/3][ticket #3]]).

- La vue dossier doit permettre de faire défiler les images d'un
  dossier comme s'il s'agissait d'un diaporama - voir [[https://github.com/Jardin-des-Sciences/website/issues/1][ticket #1]].

